### ISSUE TITLE
ncurses availability in static build

### ISSUE THREAD

**Issue by Wanninger** [userdocs/mtr-static#1]
ncurses availability

Would it be possible to compile ncurses as well next time? mtr with ncurses is an absolute must in my opinion. After all, it is quite sufficient if libncurses-dev is present at compile time.

Thanks

**Comment by userdocs** [comment]
I added [ncurses-dev](https://pkgs.alpinelinux.org/package/edge/main/x86_64/ncurses-dev) and [ncurses-static](https://pkgs.alpinelinux.org/package/edge/main/x86_64/ncurses-static)

https://github.com/userdocs/mtr-static/actions/runs/3689533893/jobs/6245582740#step:10:105

This updated the existing release so you cany try those builds

https://github.com/userdocs/mtr-static/releases/tag/0.95

**Comment by Wanninger** [comment]
...wonderful - it runs flawlessly - thank you

**Comment by userdocs** [comment]
You're welcome. I'll let you close the issue when you consider the matter resolved.
